server:
  port: 8501

spring:
  application:
    name: erp-web
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-center
      profile: dev
  #redis
  redis:
    host: 127.0.0.1 #redis的主机ip
    port: 6379
  #RabbitMq
  rabbitmq:
    host: 127.0.0.1 #rabbitmq的主机ip
    port: 5672
    username: bingo
    password: bingo
  security:
    user:
      name: bingo
      password: password123

#eureka相关配置
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8561/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5

# 或者：
feign.hystrix.enabled: false # 索性禁用feign的hystrix支持

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bingo.erp.commons.entity
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER_STR
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.bingo.erp.base.enums

management:
  endpoints:
    web:
      exposure:
        include: "*"

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

##jwt配置
tokenHead: bearer;
tokenHeader: Authorization
isRememberMeExpiresSecond: 259200 #记住账号为3天有效
audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  name: mogublog
  expiresSecond: 28800  #8个小时 3600

srcFileUrl: /Users/drew/IdeaProject/bg-erp/excel/
newFileDict: /Users/drew/IdeaProject/bg-erp/excel/