server:
  port: 9000
spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          search-paths: config-dict
          uri: https://github.com/xiahang111/bg_erp.git
          username: xiahang111
          password: xia13012256416


  security:
    user:
      name: bingo
      password: password123

#eureka相关配置
eureka:
  client:
    healthcheck:
      enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:8561/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
    lease-renewal-interval-in-seconds: 5